--- 
- :name: authlogic
- :name: tmail
- :source: http://gemcutter.org
  :name: paperclip
- :source: http://gems.github.com
  :name: openrain-action_mailer_tls
- :source: http://code.whytheluckystiff.net
  :version: ">= 4.1.1"
  :name: RedCloth
- :version: 2.3.5
  :name: rails
