--- 
- :name: authlogic
- :name: tmail
- :source: http://gemcutter.org
  :name: paperclip
- :source: http://gems.github.com
  :name: openrain-action_mailer_tls
- :name: tiny_mce
- :version: 2.3.8
  :name: rails
