--- 
- :name: authlogic
- :source: http://gemcutter.org
  :name: paperclip
- :name: tiny_mce
- :name: RedCloth
- :version: ~> 2.3.15
  :source: http://gemcutter.org
  :name: will_paginate
- :name: i18n
- :version: 2.3.8
  :name: rails
