# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen
theme: advanced
theme_advanced_toolbar_location: top
theme_advanced_resize_horizontal: true
plugins:
- table
- fullscreen
# - xhtmlxtras
- style
- paste
